# Generated by Django 5.1.1 on 2024-10-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
    ]
