# Generated by Django 5.1.1 on 2024-10-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0002_remove_menu_price'),
        ('favorite', '0003_delete_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
