# Generated by Django 5.1.1 on 2024-10-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0003_delete_menu_delete_restaurant'),
        ('adminview', '0003_menu_price'),
    ]

    operations = [
    ]
