# Generated by Django 5.1.4 on 2024-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant_name',
            field=models.CharField(default='Default Restaurant Name', max_length=255),
        ),
    ]
