# Generated by Django 5.1.4 on 2024-12-15 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('reservasi', '0002_remove_reservation_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
            preserve_default=False,
        ),
    ]
