# Generated by Django 5.1.1 on 2024-10-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_id_alter_restaurant_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
