# Generated by Django 5.1.1 on 2024-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
