# Generated by Django 5.1.1 on 2024-10-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='main.category'),
        ),
    ]
