# Generated by Django 5.1.1 on 2024-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_restaurant_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
    ]
