# Generated by Django 5.1.1 on 2024-10-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_favorite_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
